cre-ne-jp/rgrb

lib/rgrb/plugin/random_generator/constants.rb
lib/rgrb/plugin/random_generator/generator.rb
lib/rgrb/plugin/random_generator/irc_adapter.rb
lib/rgrb/plugin/random_generator/table.rb

#8 
指定した表の説明を返すコマンドを2つ追加しました。
指定した表のメタ情報"Description"を返します。
```
<nick> .rg-desc SVOC  
<RGRB> rg-desc<SVOC>: 形容詞・主語・目的語・述語を並べ、謎の短文を作ります。
```
指定した表のメタ情報から、作者(author)・作成日(added)・説明(Description)と、あれば更新日(modified)を返します。
```
<nick> .rg-info SVOC
<RGRB> rg-info<SVOC>: SVOCは、2014年12月15日にsfさんによって追加されましたの。最後に更新されたのは2014年12月20日ですわ。形容詞・主語・目的語・述語を並べ、謎の短文を作ります。
```
上記2つのコマンドを作成するうえで、コマンド定義部分の正規表現が何回も出てきていたため、改めて定数として定義し直しました。

プラグイン "Randam Generator" への新コマンド追加

---

Gemfile
Gemfile.lock
config/server_connection_report/charybdis.yaml
config/server_connection_report/test.yaml
data/server_connection_report/cre.txt
doc/plugins/server_connection_report.md
lib/rgrb/plugin/server_connection_report/atheme_services/irc_adapter.rb
lib/rgrb/plugin/server_connection_report/charybdis/irc_adapter.rb
lib/rgrb/plugin/server_connection_report/common_disposal.rb
lib/rgrb/plugin/server_connection_report/generator.rb
lib/rgrb/plugin/server_connection_report/mail_sender.rb
lib/rgrb/plugin/server_connection_report/ngircd/irc_adapter.rb
lib/rgrb/plugin/server_connection_report/test/irc_adapter.rb
spec/rgrb/plugin/server_connection_report/generator_spec.rb

issue #53 
charybdis の出力を利用してサーバーの接続・切断を検知・通知するアダプターのみ、実装完了した。
今後、#53 にて他のデーモン用アダプターやSPECの更新などを行なう。

ServerConnectionReport で、接続・切断通知をメールでも行なえるようにする

---

lib/rgrb/plugin/jihou/irc_adapter.rb

前回のマイナーバージョンアップで取り込んでいただいたコードによりバグが発生してしまったため、修正しました。
お手数ですが確認・マージをお願いいたします。
修正点
- サーバへの接続のみを検知してタイマーを起動する
- サーバ接続完了を、Numeric Reply ではなく cinch の機能で検知する
- ログが出力されるようにした

Jihou: 前回のバージョンアップで生んでしまった各種バグの修正

---

.travis.yml

Ruby 2.2.3/2.2.5/2.3.0 でのチェックを廃止し、2.2.6/2.3.3 でのチェックを増やした。

Travis-CI のチェック対象を変更

---

README.md

gem "charlock_holmes" 0.7.3 をビルドするために、which コマンドが必要でした。

必要なパッケージの追加

---

.travis.yml
Gemfile.lock

Travis-CI でチェックする Ruby 実行環境に、2017年3月22日にリリースされた v2.4.1 を追加した。
また、同時に使用しているライブラリを、2017年3月26日時点での最新版に更新した。
https://www.ruby-lang.org/ja/news/2017/03/22/ruby-2-4-1-released/

Ruby2.4.1 リリース

---

spec/rgrb/plugin/server_connection_report/atheme_services/irc_adapter_spec.rb
spec/rgrb/plugin/server_connection_report/charybdis/irc_adapter_spec.rb
spec/rgrb/plugin/server_connection_report/ngircd/irc_adapter_spec.rb

irc.cre.jp 系IRCサーバ群において、t-net.xyz サーバが廃止され、またIRC管理サービス services.cre.jp が接続されている現状に合わせるため、Rspec スクリプトを更新した。

spec_t-net2services: 廃止されたサーバを削除し、IRC管理サービス用サーバを追加

---

config/rgrb.yaml
lib/rgrb/exec/irc_bot.rb

稼働中のボットの切断メッセージにシステムシグナルが出て欲しくなかったため、設定ファイルで任意の文字列を設定できるようにしました。
設定ファイルの書き換えが必要です。

IRC ボットの QUIT メッセージを変えられるようにした

---

README.md

README-sqlite: bundle install に追加パッケージが必要になっていた

---

Gemfile
lib/rgrb/plugin/bcdice/constants.rb
lib/rgrb/plugin/bcdice/irc_adapter.rb

refs #92
ゲームシステムが見つからない、コマンドが無効の2種類のエラーが
考えられるため、それぞれの判定処理を加える。
ヘッダはランダムジェネレータを参考にして
BCDice[ユーザ名]<ゲームシステム名>
に設定する。

BCDice: ダイスボット検索処理を追加する

---

lib/rgrb/plugin/url_fetch_title/generator.rb

`rescue` の構文を間違えていたためエラーが発生していた箇所を修正しました。これにより、以下のようなエラーの発生を防ぐことができます：
https://log.irc.cre.jp/channels/write-ex2/2018/08/12#c1431790
具体的には、`rescue e` ではなく `rescue => e` が正しいというものでした。例外を変数に格納するためには `=>` が必要でした。

UrlFetchTitle: rescueの構文を間違えていた箇所を修正する

---

.travis.yml
Gemfile.lock

Travis-CI のチェック対象に、2.6.0-preview2 を追加した。

library-verUP-201809

---

.travis.yml

bundler 2.0 系列がインストールされないためにエラー終了していた。
before_install で gem update を実行することで、エラーが起こらないように修正した。

Travis-CIのチェックが、ruby260 で失敗するバグを修正

---

.travis.yml

Ruby 2.3系がEOLとなっていたので、テスト対象から外しました。

.travis.yml: Ruby 2.3.8をテスト対象から外す

---

.gitmodules

ついでに、バージョンはついていませんが、2019-07-07 現在の最新版に更新しました。

BCDice の URL を新しい物に変更した

---

lib/rgrb/exec/irc_bot.rb

先日の https://github.com/cre-ne-jp/log-archiver/pull/149 とほぼ同じ修正です。
IRCボットにおいて、`config.irc_bot['QuitMessage']` が設定されていない（nilになる）場合など、終了メッセージがStringでない場合にシグナルハンドラでエラーが発生し、終了できなくなります。`Object#to_s` を使って以上の問題を防ぎます。

IRCボット：シグナル受信で正常に終了しない問題を修正する

---

Gemfile
Gemfile.lock

#136 の立て直しです。
`bundle update` でdbmを更新できるようにするため、Gemfileにgdbmを追加しました。gdbmはRubyに標準で添付されていますが、最近gem化されたため、このようにできるようになりました。
参考：[Feature #13248: Gemify gdbm - Ruby master - Ruby Issue Tracking System](https://bugs.ruby-lang.org/issues/13248)

secret-dice: Gemfileにgdbmを追加する

---

lib/rgrb/plugin/dice_roll/generator.rb
spec/rgrb/plugin/dice_roll/generator_spec.rb

69a0fd4d94775f518506cd51c790dd6cc8ce125e の前で、データベースディレクトリ準備のエラーが発生していたため、テストを追加しました。また、親ディレクトリがない場合でもディレクトリが作成できるように、`FileUtils.mkdir_p`（`mkdir -p` と同じ処理）を使うようにしてみました。

Secret dice mkdir p

---

spec/rgrb/plugin/dice_roll/generator_spec.rb

DiceRollのテスト「出目に偏りがない」の閾値を緩くすることで、意に反してテストが失敗する確率を大幅に減らしました。正しい分布の場合に失敗する確率が10万分の1まで低下しました（これまでの失敗確率は2000回に1回でした）。このように変更しても、出目が固定されるといったバグは確実に検出できます。

DiceRoll: テスト「出目に偏りがない」で失敗する確率を減らす

---

lib/rgrb/exec/discord_bot.rb
lib/rgrb/exec/irc_bot.rb
lib/rgrb/plugin_base/adapter.rb
lib/rgrb/plugin_base/adapter_options.rb
spec/rgrb/plugin/configurable_spec.rb

fix #132 
名前を RGRB::PluginBase::AdapterOptions にしてみたが、RGRB::Config 等と同様の名前空間においた方が良かっただろうか。

アダプターの設定を渡すオブジェクトを Hash から Struct に変更

---

lib/rgrb/plugin/server_connection_report/test/irc_adapter.rb

fix #144 
以下のようなメールを送るよう、変更しました。
```mail
subject: "[TEST] IRC サーバ接続通知 (irc.kazagakure.net)"
This is TEST mail.
by RGRB::Plugin::ServerConnectionReport::Test::IrcAdapter
--
"irc.kazagakure.net" がネットワークに参加しました。
```

ServerConnectionReport::Test: テストメールであることをメールの件名・本文に明記する

---

lib/rgrb/plugin/bcdice/generator.rb
spec/rgrb/plugin/bcdice/generator_spec.rb

fix #157 
ついでに、RGRB 本体と同様に、起動時のコミット ID をメンバ変数に保存しておくようにしました。

BCDice のバージョン番号を、IRC 応答に追加

---

lib/rgrb/plugin/random_generator/generator.rb
spec/rgrb/plugin/random_generator/generator_spec.rb
spec/rgrb/plugin/server_connection_report/mail_generator_spec.rb

ランダムジェネレータのテストにおいて、`Object#send` を使って無理矢理プライベートメソッドを呼び出していた箇所を、普通のメソッド呼び出しに変えました。おそらくこれは私がインターフェースの設計に失敗していた箇所です（テストで使う＝外部から使う ⇒ publicでなければならない）。
ついでに、server_connection_reportのmail_generatorのテストの同様の箇所も修正しました。

ランダムジェネレータ：テストで必要なメソッドをpublicにする

---

lib/rgrb/plugin/bcdice/generator.rb
spec/rgrb/plugin/bcdice/generator_spec.rb

テストで無理にインスタンス変数を設定しなくてもよいように、コンストラクタでBCDiceを用意するようにしました。
また、プラグイン読み込み時のBCDiceのバージョンのログの内容を調整しました。BCDiceの用意のタイミングが変わったため、「読み込みました」と出力するのではなく、以下の図のように単にバージョン情報を出力します。

BCDice: コンストラクタでBCDiceを用意する

---

lib/rgrb/plugin/bcdice/discord_adapter.rb
lib/rgrb/plugin/bcdice/generator.rb
lib/rgrb/plugin/bcdice/irc_adapter.rb
spec/rgrb/plugin/bcdice/generator_spec.rb

fix #154
アダプタ側でのジェネレータ読み込み方法を改善しました。
テストでの処理が複雑化してしまっていますが、他の何か良い方法はあるでしょうか。

Bcdice: テストに失敗するようになったのを修正

---

lib/rgrb/plugin/server_connection_report/irc_adapter_methods.rb
lib/rgrb/plugin_base/adapter.rb
lib/rgrb/plugin_base/adapter_options.rb
lib/rgrb/plugin_base/discord_adapter.rb
lib/rgrb/plugin_base/generator.rb
lib/rgrb/plugin_base/irc_adapter.rb
spec/rgrb/plugin/bcdice/generator_spec.rb
spec/rgrb/plugin/random_generator/generator_spec.rb
spec/rgrb/plugin/server_connection_report/mail_generator_spec.rb

https://github.com/cre-ne-jp/rgrb/pull/155#issuecomment-515761645 で書かれた、ジェネレータに渡すロガー関連の処理の変更です。
* ジェネレータの既定の（アダプタを使わないときの）ロガーとして、`RGRB::PluginBase::Adapter` 内に共通のロガー `DEFAULT_LOGGER` を用意します。このようにすることで、ジェネレータのテスト時にロガーを用意しなくてもよくなります。プラグインごとにロガーを作らないので、リソースの消費も少ないです。
* アダプタを使うとき、ジェネレータに以下をロガーとして渡します。
* IRCアダプタ：アダプタ自身（アダプタに見やすいロガー機能が含まれているため）
* Discordアダプタ：ボットが持つロガー（Cinchのように見やすいロガーが含まれていないため）

ジェネレータに渡すロガー関連の処理の簡略化

---

lib/rgrb/plugin/ctcp/irc_adapter.rb

`CLIENTINFO` で送信する、利用可能なCTCPコマンドをクラス定数で定義するようにしました。一箇所で定義して漏れがないようにする狙いです。
また、コメントを追加して、元PR #173 に記載されていたRFCドラフトの該当箇所へのリンクを示しました。

CTCP: コマンド一覧の改良とコメントの追加

---

lib/rgrb/plugin/ctcp/irc_adapter.rb

timeライブラリを使い、`strftime` の部分を簡潔に書きました。

CTCP: TIMEの応答をRFC 2822形式で返す

---

lib/rgrb/plugin/ctcp/irc_adapter.rb

* RFC に従い、CTCP-TIME 応答の形式を修正した
- https://tools.ietf.org/id/draft-oakley-irc-ctcp-01.html
* ログを残すようにした (fix: #148)
* 自分(と同じNICKの他のクライアントを含む)が発信した CTCP 要求には応答しないようにした

IRC 版のプラグイン Ctcp を修正

---

lib/rgrb/plugin_base/irc_adapter.rb
lib/rgrb/plugins_loader.rb
spec/rgrb/plugins_loader_spec.rb

[CodeClimate](https://codeclimate.com/github/cre-ne-jp/rgrb)でCognitive Complexity（コードの複雑さ）が大きいと指摘されたメソッドを分割して、処理を単純にしました。

メソッド分割による処理の単純化

---

.travis.yml

マイナーバージョンのみを指定することで、各マイナーバージョンの最新版がテストされるようにしました。
* 2.5→2.5.8
* 2.6→2.6.6
* 2.7→2.7.1

Travis CI: パッチバージョンを指定しない

---

lib/rgrb/plugin/keyword/generator.rb
spec/rgrb/plugin/keyword/generator_spec.rb

ハードコートされている CRE サーチへのURLを、ログアーカイブのキーワード検索ページへの URL に変更しました。
そもそもハードコートではなく、設定ファイルで変更できるようにした方が便利でしょうか？

keyword: キーワード検索の URL を、ログアーカイブのキーワード検索ページに変更

---

lib/rgrb/plugin/url_fetch_title/generator.rb

Fixes #190 
Gem http v4のインターフェースに合わせて、HTTP.timeoutを操作別に指定するときは、第1引数にHashを指定するようにします。

UrlFetchTitle: タイムアウト指定の引数を修正する

---

.gitmodules
Gemfile
Gemfile.lock
lib/rgrb/plugin/bcdice/discord_adapter.rb
lib/rgrb/plugin/bcdice/errors.rb
lib/rgrb/plugin/bcdice/generator.rb
lib/rgrb/plugin/bcdice/irc_adapter.rb
spec/rgrb/plugin/bcdice/generator_spec.rb

gem になった BCDice ライブラリを使うようにしました。
現段階ではまだテストバージョンですが、問題なく動作していると思います。

BCDice ライブラリを v2 から v3 に更新

---

lib/rgrb/plugin/online_session_search/generator.rb

Ruby 3では、OnlineSessionSearchのみで問題が起こっていました。Ruby 3からopen-uriライブラリで `Kernel.#open` が使えなくなったため、`OpenURI.#open_uri` を使うようにして解消できました。

Ruby 3に対応させる

---

Gemfile.lock

ライブラリの更新(202102)

---

.github/workflows/coverage.yaml
.github/workflows/test.yaml

Ubuntu 20.04に更新されてlibgdbm5が使えなくなったため。

GitHub Actions: libgdbm6をインストールする

---

README.md

git submodule でのインストールについて記述が残っていたので、削除しました。

ドキュメントにBCDice を gem 経由でインストールすることを反映

---

.github/workflows/test.yaml
Gemfile.lock

サポートが切れ、bcdice 3.5.0 が対応していない ruby 2.5 系列でのテストを廃止した。

ライブラリの更新 (202112)

---

.github/workflows/test.yaml
Gemfile
Gemfile.lock
README.md

activesupport を 8.x 系列へ更新を含む。
これにより、Ruby 3.1 未満のサポートを終了する。

ライブラリの更新 (202412)
